using Dapper.Npa.Generator.Models;
using Dapper.Npa.Generator.Utils;

namespace Dapper.Npa.Generator.Emitters;

using System.Collections.Generic;
using System.Linq;
using System.Text;
using Generator.Emitters;
using Generator.Models;
using Generator.Utils;

internal static class DiExtensionEmitter
{
    /// <summary>
    /// Emits DapperXServiceCollectionExtensions.g.cs.
    ///
    /// Each generated {Name}RepositoryImpl already declares the [Repository] interface in its
    /// base-type list, so AddScoped&lt;IXxxRepository, XxxRepositoryImpl&gt;() works directly.
    /// IDbConnection is registered once as scoped from the caller-supplied factory and then
    /// injected into every Impl constructor automatically by ASP.NET Core DI.
    /// </summary>
    public static string Emit(
        IReadOnlyList<EntityModel> models,
        IReadOnlyDictionary<string, RepositoryInterfaceModel> interfaceByEntityFqn)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Data;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using Dapper.Npa.Abstractions.Repositories;");
        sb.AppendLine();
        // Place in Microsoft.Extensions.DependencyInjection so the extension method is
        // available anywhere IServiceCollection is used — no extra using required.
        sb.AppendLine("namespace Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();
        sb.AppendLine("public static class DapperXServiceCollectionExtensions");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Registers all Dapper Nparepository implementations with the DI container.");
        sb.AppendLine("    /// IDbConnection is registered as scoped using the supplied factory.");
        sb.AppendLine("    /// Inject IProductRepository (or IRepository&lt;Product, int&gt;) in your services.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static IServiceCollection AddDapperXRepositories(");
        sb.AppendLine("        this IServiceCollection services,");
        sb.AppendLine("        Func<IServiceProvider, IDbConnection> connectionFactory)");
        sb.AppendLine("    {");
        sb.AppendLine("        services.AddScoped<IDbConnection>(connectionFactory);");
        sb.AppendLine();

        foreach (var model in models)
        {
            var entityFqn = model.FullyQualifiedName;
            interfaceByEntityFqn.TryGetValue(entityFqn, out var repoInterface);

            var implName = repoInterface?.ImplClassName ?? model.RepositoryImplClassName;
            var implNs = repoInterface?.Namespace
                ?? (string.IsNullOrEmpty(model.Namespace) ? "Generated" : $"{model.Namespace}.Generated");
            var implFqn = string.IsNullOrEmpty(implNs) ? implName : $"{implNs}.{implName}";

            var idType = GetIdTypeName(model);
            var baseIface = $"global::Dapper.Npa.Abstractions.Repositories.IRepository<global::{entityFqn}, {idType}>";

            sb.AppendLine($"        // {model.ClassName}");

            if (repoInterface is not null)
            {
                // Impl already declares IXxxRepository — use the clean two-argument overload.
                var ifaceFqn = repoInterface.InterfaceFqn.StartsWith("global::", StringComparison.Ordinal)
                    ? repoInterface.InterfaceFqn
                    : $"global::{repoInterface.InterfaceFqn}";
                sb.AppendLine($"        services.AddScoped<{ifaceFqn}, global::{implFqn}>();");
                // Forward IRepository<TEntity, TId> to the same scoped instance.
                sb.AppendLine($"        services.AddScoped<{baseIface}>(sp =>");
                sb.AppendLine($"            sp.GetRequiredService<{ifaceFqn}>());");
            }
            else
            {
                // No custom interface — register concrete + forward base interface.
                sb.AppendLine($"        services.AddScoped<global::{implFqn}>();");
                sb.AppendLine($"        services.AddScoped<{baseIface}>(sp =>");
                sb.AppendLine($"            sp.GetRequiredService<global::{implFqn}>());");
            }

            sb.AppendLine();
        }

        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string GetIdTypeName(EntityModel model)
    {
        if (model.CompositeKey is not null)
            return CompositeKeySqlHelper.FormatClrType(model.CompositeKey.KeyTypeName);

        var idProp = model.Properties.FirstOrDefault(p => p.IsId);
        if (idProp is null)
            return "object";

        return CompositeKeySqlHelper.FormatClrType(idProp.ClrTypeName);
    }
}
