using Dapper.Npa.Generator.Builders;
using Dapper.Npa.Generator.Generators;
using Dapper.Npa.Generator.Models;
using Dapper.Npa.Generator.Utils;

namespace Dapper.Npa.Generator.Emitters;

using System.Linq;
using System.Text;
using Generator.Builders;
using Generator.Generators;
using Generator.Models;
using Generator.Utils;
using Microsoft.CodeAnalysis;

internal static class RepositoryEmitter
{
    public static string Emit(
        EntityModel entity,
        string provider,
        RepositoryInterfaceModel? repositoryInterface,
        SourceProductionContext spc,
        IReadOnlyDictionary<string, EntityModel> allModels,
        Compilation compilation)
    {
        var sb = new StringBuilder();
        var idType = CompositeKeySqlHelper.FormatClrType(
            CompositeKeySqlHelper.ResolveIdTypeName(entity, repositoryInterface));
        var entityFqn = entity.FullyQualifiedName;

        var implClassName = repositoryInterface?.ImplClassName
            ?? RepositoryNaming.DefaultImplClassName(entity.ClassName);
        var ns = repositoryInterface?.Namespace
            ?? (string.IsNullOrEmpty(entity.Namespace) ? "Generated" : $"{entity.Namespace}.Generated");

        var readPair = entity.SoftDeleteColumn is not null
            ? SoftDeleteSqlBuilder.BuildReadSqlPair(entity, provider)
            : null;
        var selectSql = readPair?.SelectAll ?? SqlBuilder.BuildSelect(entity, provider: provider);
        var selectByIdSql = readPair?.SelectById ?? SqlBuilder.BuildSelectById(entity, provider: provider);
        var selectByIdsSql = readPair?.SelectByIds ?? SqlBuilder.BuildSelectByIds(entity, provider: provider);
        var existsSql = readPair?.Exists ?? SqlBuilder.BuildExists(entity, provider: provider);
        var countSql = readPair?.Count ?? SqlBuilder.BuildCount(entity, provider: provider);
        var insertSql = SqlBuilder.BuildInsert(entity, provider);
        var updateSql = entity.IsImmutable ? string.Empty : SqlBuilder.BuildUpdate(entity, provider);
        var deleteSql = entity.IsImmutable ? string.Empty : SqlBuilder.BuildDelete(entity, provider);
        var deleteByIdSql = entity.IsImmutable ? string.Empty : SqlBuilder.BuildDeleteById(entity, provider);
        var deleteAllSql = entity.IsImmutable ? string.Empty : SqlBuilder.BuildDeleteAllByIds(entity, provider);
        var hardDeleteSql = entity.SoftDeleteColumn is not null && !entity.IsImmutable
            ? SqlBuilder.BuildHardDelete(entity)
            : null;
        var pageSql = readPair?.SelectAllPage ?? SqlBuilder.AppendPaging(selectSql, provider, entity);
        var sliceSql = readPair?.SelectAllSlice ?? SqlBuilder.AppendSlicePaging(selectSql, provider, entity);
        var countPageSql = readPair?.CountPage ?? SqlBuilder.BuildCountForPage(entity, provider: provider);
        var upsertSql = UpsertSqlBuilder.Build(entity, provider);

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// This file is generated by Dapper Npaat compile time. Do not edit.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Data;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Dapper;");
        sb.AppendLine("using Dapper.Npa.Abstractions.Exceptions;");
        sb.AppendLine("using Dapper.Npa.Abstractions.Paging;");
        sb.AppendLine("using Dapper.Npa.Abstractions.Repositories;");
        sb.AppendLine("using Dapper.Npa.Abstractions.Sorting;");
        sb.AppendLine("using Dapper.Npa.Batching.Batch;");
        sb.AppendLine("using Dapper.Npa.Runtime.Repositories;");
        sb.AppendLine("using Dapper.Npa.Runtime.Execution;");
        if (entity.HasLifecycle)
            sb.AppendLine("using Dapper.Npa.Lifecycle.Invokers;");
        if (entity.Auditing is not null)
            sb.AppendLine("using Dapper.Npa.Abstractions.Auditing;");
        if (entity.TenantIdColumn is not null)
            sb.AppendLine("using Dapper.Npa.Abstractions.Tenancy;");
        if (entity.Sequence is not null)
            sb.AppendLine("using Dapper.Npa.Abstractions.Sequences;");
        sb.AppendLine("using Dapper.Npa.Abstractions.Configuration;");
        sb.AppendLine("using Dapper.Npa.Core.Enums;");
        if (repositoryInterface?.DeclaredMethods.Any(m =>
                SyntaxHelper.GetAttribute(m, SyntaxHelper.StoredProcedureAttr) is not null) == true)
            sb.AppendLine("using Dapper.Npa.Abstractions.StoredProcedures;");
        sb.AppendLine("using Dapper.Npa.Abstractions.Query;");
        sb.AppendLine("using Dapper.Npa.Runtime.Query;");
        if (entity.Relationships.Any(r => r.IsBatchLoadable && r.ChildHasPostLoad))
        {
            var childNamespaces = entity.Relationships
                .Where(r => r.IsBatchLoadable && r.ChildHasPostLoad && !string.IsNullOrEmpty(r.ChildEntityFqn))
                .Select(r => GetChildOutputNamespace(r.ChildEntityFqn!, allModels))
                .Distinct(StringComparer.Ordinal);
            foreach (var childNs in childNamespaces)
                sb.AppendLine($"using {childNs};");
        }
        if (!entity.IsImmutable || entity.Relationships.Any(r => r.IsBatchLoadable) || entity.RequiresDbRow)
            sb.AppendLine("using System.Linq;");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine();

        EmitSortFragmentConstants(sb, entity);

        var baseTypes = repositoryInterface is not null
            ? $"DapperXRepositoryBase<{entityFqn}, {idType}>, {repositoryInterface.InterfaceFqn}"
            : $"DapperXRepositoryBase<{entityFqn}, {idType}>";

        sb.AppendLine($"public sealed class {implClassName} : {baseTypes}");
        sb.AppendLine("{");
        sb.AppendLine($"    protected override DatabaseProvider Provider => {ToProviderEnum(provider)};");
        sb.AppendLine();

        EmitFilterConstants(sb, entity, provider);
        foreach (var child in GlobalFilterGenerator.GetLazyChildrenWithFilters(entity, allModels))
            EmitChildFilterConstants(sb, child, provider);

        RepositoryEmission.EmitConstructorExtras(sb, entity, allModels, provider);
        EmitConstructor(sb, implClassName, entity, allModels, provider);

        EmitLifecycleHooks(sb, entity);
        EmitDeleteByIdWithRemoveHooks(sb, entity, idType);

        EmitResolveColumn(sb, entity);

        EmbeddedMappingEmitter.EmitDbRowAndMapping(sb, entity, compilation);

        if (BulkInsertEligibility.IsEligible(entity, provider))
        {
            BulkInsertGenerator.EmitMetadata(sb, entity);
            BulkInsertGenerator.EmitRowBuilderMethod(sb, entity, entityFqn);
        }

        var projections = ProjectionCollector.Collect(compilation, entity, spc);
        QueryGenerator.Emit(sb, entity, provider, allModels, projections, spc);

        EmitSqlPropertyOverrides(sb, entity, provider, readPair, selectByIdSql, selectSql, selectByIdsSql, existsSql, countSql,
            insertSql, updateSql, deleteSql, deleteByIdSql, deleteAllSql, pageSql, sliceSql, countPageSql, upsertSql);

        EmitSortFragmentOverride(sb, entity);

        if (entity.IsImmutable)
            EmitImmutableMutatingOverrides(sb, entityFqn, idType);

        RepositoryEmission.EmitAll(sb, entity, entityFqn, idType, provider);
        if (hardDeleteSql is not null)
            RepositoryEmission.EmitHardDeleteAsync(sb, entityFqn, hardDeleteSql, entity);

        GraphGenerator.Emit(sb, entity, entityFqn, idType, allModels, spc);

        var insertPlan = ExecutionPlanGenerator.BuildInsertPlan(entity, allModels);
        var deletePlan = ExecutionPlanGenerator.BuildDeletePlan(entity, allModels);
        ExecutionPlanEmitter.Emit(sb, insertPlan, deletePlan);

        ElementCollectionGenerator.Emit(sb, entity, entityFqn, idType);
        NamedEntityGraphGenerator.Emit(sb, entity, entityFqn, idType, allModels, provider);

        UpsertGenerator.EmitMethodOverrides(sb, entity, entityFqn);

        if (GlobalFilterGenerator.GetLazyChildrenWithFilters(entity, allModels).Any())
            GlobalFilterGenerator.EmitChildApplyFiltersMethods(sb, entity, allModels);

        BatchRelationshipLoaderGenerator.EmitChildLifecycleFields(sb, entity, allModels);
        BatchRelationshipLoaderGenerator.Emit(sb, entity, allModels, provider);

        if (LazyLoaderGenerator.NeedsPostLoadWiring(entity))
            LazyLoaderGenerator.Emit(sb, entity, allModels, provider);

        MethodNameEmitter.EmitBaseMethodWrappers(sb, entity, entityFqn, idType);

        if (repositoryInterface?.DeclaredMethods is { Count: > 0 } methods)
        {
            foreach (var method in methods)
            {
                var methodSource = DerivedQueryGenerator.TryEmitMethod(
                    method, entity, provider, compilation, spc, allModels);
                if (methodSource is not null)
                    sb.AppendLine(methodSource);
            }
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string GetChildOutputNamespace(string childFqn, IReadOnlyDictionary<string, EntityModel> allModels)
    {
        foreach (var model in allModels.Values)
        {
            if (model.FullyQualifiedName == childFqn
                || NormalizeChildFqn(model.FullyQualifiedName) == NormalizeChildFqn(childFqn))
            {
                return string.IsNullOrEmpty(model.Namespace) ? "Generated" : model.Namespace;
            }
        }

        return "Generated";
    }

    private static string NormalizeChildFqn(string fqn)
        => fqn.StartsWith("global::", StringComparison.Ordinal) ? fqn.Substring("global::".Length) : fqn;

    private static void EmitFilterConstants(StringBuilder sb, EntityModel entity, string provider)
    {
        if (!entity.GlobalFilters.Any())
            return;

        foreach (var gf in entity.GlobalFilters)
            sb.AppendLine($"    private static readonly string {gf.ConstantName} = \" AND {EscapeFilterCondition(gf.Condition, provider)}\";");
        sb.AppendLine();
    }

    private static void EmitChildFilterConstants(StringBuilder sb, EntityModel child, string provider)
    {
        if (!child.GlobalFilters.Any())
            return;

        sb.AppendLine($"file static class {child.ClassName}Filters");
        sb.AppendLine("{");
        foreach (var gf in child.GlobalFilters)
            sb.AppendLine($"    public const string {gf.ConstantName} = \" AND {EscapeFilterCondition(gf.Condition, provider)}\";");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static string EscapeFilterCondition(string condition, string provider)
        => ProviderSqlHelper.NormalizeBooleanLiteralsInCondition(condition, provider)
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"");

    private static void EmitSortFragmentConstants(StringBuilder sb, EntityModel entity)
    {
        var sortableProps = entity.Properties.Where(p => p.IsSortable).ToList();
        if (sortableProps.Count == 0)
            return;

        sb.AppendLine($"file static class {entity.ClassName}SortFragments");
        sb.AppendLine("{");
        foreach (var p in sortableProps)
        {
            sb.AppendLine($"    public static readonly string {p.PropertyName}Asc  = \" ORDER BY {p.ColumnName} ASC\";");
            sb.AppendLine($"    public static readonly string {p.PropertyName}Desc = \" ORDER BY {p.ColumnName} DESC\";");
        }
        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static void EmitLifecycleHooks(StringBuilder sb, EntityModel entity)
    {
        if (!entity.LifecycleMethods.Any(m =>
                m.Kind is LifecycleKind.PrePersist or LifecycleKind.PostPersist
                    or LifecycleKind.PreUpdate or LifecycleKind.PostUpdate
                    or LifecycleKind.PreRemove or LifecycleKind.PostRemove
                    or LifecycleKind.PostLoad)
            && !entity.EntityListenerTypes.Any())
            return;

        sb.AppendLine($"    private readonly {entity.ClassName}LifecycleInvoker _lifecycle = new();");
        sb.AppendLine();
        EmitLifecycleOverride(sb, entity, LifecycleKind.PrePersist, "OnPrePersist", "InvokePrePersist");
        EmitLifecycleOverride(sb, entity, LifecycleKind.PostPersist, "OnPostPersist", "InvokePostPersist");
        EmitLifecycleOverride(sb, entity, LifecycleKind.PreUpdate, "OnPreUpdate", "InvokePreUpdate");
        EmitLifecycleOverride(sb, entity, LifecycleKind.PostUpdate, "OnPostUpdate", "InvokePostUpdate");
        EmitLifecycleOverride(sb, entity, LifecycleKind.PreRemove, "OnPreRemove", "InvokePreRemove");
        EmitLifecycleOverride(sb, entity, LifecycleKind.PostRemove, "OnPostRemove", "InvokePostRemove");
        if (!LazyLoaderGenerator.NeedsPostLoadWiring(entity))
            EmitLifecycleOverride(sb, entity, LifecycleKind.PostLoad, "OnPostLoad", "InvokePostLoad");
    }

    private static void EmitLifecycleOverride(
        StringBuilder sb,
        EntityModel entity,
        LifecycleKind kind,
        string baseHookName,
        string invokerMethod)
    {
        if (!entity.HasLifecycleHook(kind))
            return;

        sb.AppendLine(
            $"    protected override void {baseHookName}({entity.FullyQualifiedName} entity) => _lifecycle.{invokerMethod}(entity);");
        sb.AppendLine();
    }

    private static void EmitDeleteByIdWithRemoveHooks(StringBuilder sb, EntityModel entity, string idType)
    {
        if (!entity.HasRemoveHooks)
            return;

        var entityFqn = entity.FullyQualifiedName;
        var tenantSuffix = entity.TenantIdColumn is not null ? ", tenantId = _tenantProvider?.GetCurrentTenantId()" : string.Empty;
        sb.AppendLine($"    public override async Task DeleteByIdAsync({idType} id, IDbTransaction? transaction = null, CancellationToken ct = default)");
        sb.AppendLine("    {");
        sb.AppendLine("        const string MethodName = \"DeleteByIdAsync\";");
        if (entity.GlobalFilters.Any())
        {
            SoftDeleteBypassHelper.EmitBaseSqlVariable(sb, entity, "SelectById");
            var selectExpr = SoftDeleteBypassHelper.HasSoftDelete(entity) ? "ApplyGlobalFilters(baseSql)" : "ApplyGlobalFilters(SelectByIdSql)";
            EntityQueryEmitter.EmitQueryFirstOrDefaultAsync(sb, entity, entityFqn,
                selectExpr, $"new {{ {ParameterBindingHelper.IdAssignment(entity)}{tenantSuffix} }}", "transaction", "entity");
        }
        else
        {
            EntityQueryEmitter.EmitQueryFirstOrDefaultAsync(sb, entity, entityFqn,
                "SelectByIdSql", $"new {{ {ParameterBindingHelper.IdAssignment(entity)}{tenantSuffix} }}", "transaction", "entity");
        }
        sb.AppendLine("        if (entity is null)");
        sb.AppendLine("            return;");
        sb.AppendLine("        OnPreRemove(entity);");
        var deleteSql = entity.GlobalFilters.Any() ? "ApplyGlobalFilters(DeleteByIdSql)" : "DeleteByIdSql";
        sb.AppendLine(entity.TenantIdColumn is not null
            ? $"        await DbExecutor.ExecuteAsync(_connection, {deleteSql}, new {{ {ParameterBindingHelper.IdAssignment(entity)}, tenantId = _tenantProvider?.GetCurrentTenantId() }}, transaction, logContext: DbExecutor.CreateLogContext(MethodName, Options, Provider));"
            : $"        await DbExecutor.ExecuteAsync(_connection, {deleteSql}, new {{ {ParameterBindingHelper.IdAssignment(entity)} }}, transaction, logContext: DbExecutor.CreateLogContext(MethodName, Options, Provider));");
        sb.AppendLine("        OnPostRemove(entity);");
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void EmitConstructor(StringBuilder sb, string implClassName, EntityModel entity, IReadOnlyDictionary<string, EntityModel> allModels, string provider)
    {
        var hasAuditing = entity.Auditing is not null;
        var hasTenant = entity.TenantIdColumn is not null;
        var hasSequence = entity.Sequence is not null;

        sb.Append($"    public {implClassName}(IDbConnection connection, IDapperXOptions? options = null");
        if (hasAuditing)
            sb.Append(", IAuditingProvider? auditingProvider = null");
        if (hasTenant)
            sb.Append(", ITenantProvider? tenantProvider = null");
        if (hasSequence)
            sb.Append(", ISequenceAllocator? sequenceAllocator = null");
        sb.AppendLine(")");
        sb.AppendLine("        : base(connection)");
        sb.AppendLine("    {");
        sb.AppendLine("        Options = options;");
        RepositoryEmission.EmitConstructorAssignments(sb, entity, allModels, provider);
        sb.AppendLine("    }");
        sb.AppendLine();

        if (entity.TenantIdColumn is not null)
        {
            TenancyGenerator.EmitApplyTenantIdMethod(sb, entity);
            TenancyGenerator.EmitWithTenantParamsMethod(sb, entity);
        }
    }

    private static void EmitResolveColumn(StringBuilder sb, EntityModel entity)
    {
        sb.AppendLine("    /// <summary>Maps property name to column name — compile-time switch, no reflection.</summary>");
        sb.AppendLine("    public static string ResolveColumn(string propertyName) => propertyName switch");
        sb.AppendLine("    {");
        foreach (var p in entity.Properties.Where(p => !p.IsTransient && p.Formula is null))
        {
            var key = p.IsEmbeddedColumn
                ? $"\"{p.PropertyName}\""
                : $"nameof({entity.FullyQualifiedName}.{p.PropertyName})";
            sb.AppendLine($"        {key} => \"{p.ColumnName}\",");
        }
        sb.AppendLine($"        _ => throw new UnmappedPropertyException(typeof({entity.FullyQualifiedName}), propertyName),");
        sb.AppendLine("    };");
        sb.AppendLine();
    }

    private static void EmitSqlPropertyOverrides(
        StringBuilder sb,
        EntityModel entity,
        string provider,
        SoftDeleteSqlBuilder.ReadSqlPair? readPair,
        string selectByIdSql,
        string selectSql,
        string selectByIdsSql,
        string existsSql,
        string countSql,
        string insertSql,
        string updateSql,
        string deleteSql,
        string deleteByIdSql,
        string deleteAllSql,
        string pageSql,
        string sliceSql,
        string countPageSql,
        string upsertSql)
    {
        EmitSqlProperty(sb, "SelectByIdSql", selectByIdSql);
        if (readPair?.SelectByIdIncludingDeleted is not null)
            EmitSqlPrivateConst(sb, "SelectByIdSqlIncludingDeleted", readPair.SelectByIdIncludingDeleted);
        EmitSqlProperty(sb, "SelectAllSql", selectSql);
        if (readPair?.SelectAllIncludingDeleted is not null)
            EmitSqlPrivateConst(sb, "SelectAllSqlIncludingDeleted", readPair.SelectAllIncludingDeleted);
        EmitSqlProperty(sb, "SelectByIdsSql", selectByIdsSql);
        if (readPair?.SelectByIdsIncludingDeleted is not null)
            EmitSqlPrivateConst(sb, "SelectByIdsSqlIncludingDeleted", readPair.SelectByIdsIncludingDeleted);
        EmitSqlProperty(sb, "ExistsSql", existsSql);
        if (readPair?.ExistsIncludingDeleted is not null)
            EmitSqlPrivateConst(sb, "ExistsSqlIncludingDeleted", readPair.ExistsIncludingDeleted);
        EmitSqlProperty(sb, "CountSql", countSql);
        if (readPair?.CountIncludingDeleted is not null)
            EmitSqlPrivateConst(sb, "CountSqlIncludingDeleted", readPair.CountIncludingDeleted);
        EmitSqlProperty(sb, "SelectAllPageSql", pageSql);
        if (readPair?.SelectAllPageIncludingDeleted is not null)
            EmitSqlPrivateConst(sb, "SelectAllPageSqlIncludingDeleted", readPair.SelectAllPageIncludingDeleted);
        EmitSqlProperty(sb, "SelectAllSliceSql", sliceSql);
        if (readPair?.SelectAllSliceIncludingDeleted is not null)
            EmitSqlPrivateConst(sb, "SelectAllSliceSqlIncludingDeleted", readPair.SelectAllSliceIncludingDeleted);
        EmitSqlProperty(sb, "CountPageSql", countPageSql);
        if (readPair?.CountPageIncludingDeleted is not null)
            EmitSqlPrivateConst(sb, "CountPageSqlIncludingDeleted", readPair.CountPageIncludingDeleted);

        if (entity.IsImmutable)
        {
            EmitSqlProperty(sb, "InsertSql", "SELECT 1 WHERE 1 = 0");
            EmitSqlProperty(sb, "UpdateSql", "SELECT 1 WHERE 1 = 0");
            EmitSqlProperty(sb, "DeleteSql", "SELECT 1 WHERE 1 = 0");
            EmitSqlProperty(sb, "DeleteByIdSql", "SELECT 1 WHERE 1 = 0");
            EmitSqlProperty(sb, "DeleteByIdsSql", "SELECT 1 WHERE 1 = 0");
        }
        else
        {
            EmitSqlProperty(sb, "InsertSql", insertSql);
            EmitSqlProperty(sb, "UpdateSql", updateSql);
            EmitSqlProperty(sb, "DeleteSql", deleteSql);
            EmitSqlProperty(sb, "DeleteByIdSql", deleteByIdSql);
            EmitSqlProperty(sb, "DeleteByIdsSql", deleteAllSql);
            if (entity.Sequence is not null)
                sb.AppendLine($"    private const string SequenceNextSql = \"{EscapeString(SqlBuilder.BuildSequenceNextSql(provider, entity.Sequence.SequenceName))}\";");
        }

        EmitSqlProperty(sb, "UpsertSql", upsertSql);
        sb.AppendLine();
    }

    private static void EmitSqlProperty(StringBuilder sb, string name, string sql)
        => sb.AppendLine($"    protected override string {name} => \"{EscapeString(sql)}\";");

    private static void EmitSqlPrivateConst(StringBuilder sb, string name, string sql)
        => sb.AppendLine($"    private const string {name} = \"{EscapeString(sql)}\";");

    private static void EmitSortFragmentOverride(StringBuilder sb, EntityModel entity)
    {
        var sortableProps = entity.Properties.Where(p => p.IsSortable).ToList();
        if (sortableProps.Count == 0)
            return;

        sb.AppendLine("    protected override string GetSortFragment(Sort sort) => sort.Column switch");
        sb.AppendLine("    {");
        foreach (var p in sortableProps)
        {
            sb.AppendLine($"        nameof({entity.FullyQualifiedName}.{p.PropertyName}) when sort.Ascending => {entity.ClassName}SortFragments.{p.PropertyName}Asc,");
            sb.AppendLine($"        nameof({entity.FullyQualifiedName}.{p.PropertyName}) when !sort.Ascending => {entity.ClassName}SortFragments.{p.PropertyName}Desc,");
        }
        sb.AppendLine("        _ => throw new InvalidSortException(sort.Column),");
        sb.AppendLine("    };");
        sb.AppendLine();
    }

    private static void EmitImmutableMutatingOverrides(StringBuilder sb, string entityFqn, string idType)
    {
        const string msg = "Entity is marked [Immutable].";
        sb.AppendLine($"    public override Task InsertAsync({entityFqn} entity, IDbTransaction? transaction = null, CancellationToken ct = default)");
        sb.AppendLine($"        => throw new NotSupportedException(\"{msg}\");");
        sb.AppendLine();
        sb.AppendLine($"    public override Task UpdateAsync({entityFqn} entity, IDbTransaction? transaction = null, CancellationToken ct = default)");
        sb.AppendLine($"        => throw new NotSupportedException(\"{msg}\");");
        sb.AppendLine();
        sb.AppendLine($"    public override Task DeleteAsync({entityFqn} entity, IDbTransaction? transaction = null, CancellationToken ct = default)");
        sb.AppendLine($"        => throw new NotSupportedException(\"{msg}\");");
        sb.AppendLine();
        sb.AppendLine($"    public override Task DeleteByIdAsync({idType} id, IDbTransaction? transaction = null, CancellationToken ct = default)");
        sb.AppendLine($"        => throw new NotSupportedException(\"{msg}\");");
        sb.AppendLine();
        sb.AppendLine($"    public override Task DeleteAllByIdAsync(IEnumerable<{idType}> ids, IDbTransaction? transaction = null, CancellationToken ct = default)");
        sb.AppendLine($"        => throw new NotSupportedException(\"{msg}\");");
        sb.AppendLine();
        sb.AppendLine($"    public override Task UpsertAsync({entityFqn} entity, IDbTransaction? transaction = null, CancellationToken ct = default)");
        sb.AppendLine($"        => throw new NotSupportedException(\"{msg}\");");
        sb.AppendLine();
        sb.AppendLine($"    public override Task UpsertManyAsync(IEnumerable<{entityFqn}> entities, IDbTransaction? transaction = null, CancellationToken ct = default, int? batchSize = null)");
        sb.AppendLine($"        => throw new NotSupportedException(\"{msg}\");");
        sb.AppendLine();
    }

    private static string EscapeString(string s)
        => s.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\n", " ").Replace("\r", "");

    private static string ToProviderEnum(string provider)
        => provider switch
        {
            "PostgreSql" => "DatabaseProvider.PostgreSql",
            "MySql" => "DatabaseProvider.MySql",
            "Sqlite" => "DatabaseProvider.Sqlite",
            _ => "DatabaseProvider.SqlServer",
        };
}
