namespace DapperX.Generator.Emitters;

using System;
using System.Text;

internal static class ConnectionFactoryEmitter
{
    public static string Emit(string provider)
    {
        var (connectionType, openNamespace) = provider switch
        {
            "SqlServer" => ("global::Microsoft.Data.SqlClient.SqlConnection", "Microsoft.Data.SqlClient"),
            "PostgreSql" => ("global::Npgsql.NpgsqlConnection", "Npgsql"),
            "MySql" => ("global::MySqlConnector.MySqlConnection", "MySqlConnector"),
            "Sqlite" => ("global::Microsoft.Data.Sqlite.SqliteConnection", "Microsoft.Data.Sqlite"),
            _ => throw new ArgumentOutOfRangeException(nameof(provider), provider, "Unknown database provider."),
        };

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System.Data;");
        sb.AppendLine();
        sb.AppendLine($"using {openNamespace};");
        sb.AppendLine();
        sb.AppendLine("namespace DapperX.Generated;");
        sb.AppendLine();
        sb.AppendLine("public static class DapperXConnectionFactory");
        sb.AppendLine("{");
        sb.AppendLine($"    public const string ProviderName = \"{provider}\";");
        sb.AppendLine();
        sb.AppendLine("    public static IDbConnection CreateConnection(string connectionString)");
        sb.AppendLine($"        => new {connectionType}(connectionString);");
        sb.AppendLine();
        sb.AppendLine("    public static IDbConnection CreateOpenConnection(string connectionString)");
        sb.AppendLine("    {");
        sb.AppendLine("        var connection = CreateConnection(connectionString);");
        sb.AppendLine("        connection.Open();");
        sb.AppendLine("        return connection;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}
