using DapperX.Generator.Models;

namespace DapperX.Generator.Emitters;

using System.Linq;
using System.Text;
using Generator.Models;

internal static class LifecycleEmitter
{
    public static string? Emit(EntityModel entity, string outputNamespace)
    {
        var hasEntityHooks = entity.LifecycleMethods.Any(m => IsEntityHook(m.Kind));
        var hasListeners = entity.EntityListenerTypes.Any();
        if (!hasEntityHooks && !entity.HasBatchLifecycle && !hasListeners)
            return null;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using DapperX.Lifecycle.Invokers;");
        if (entity.HasBatchLifecycle)
            sb.AppendLine("using DapperX.Lifecycle.Batch;");
        sb.AppendLine();
        sb.AppendLine($"namespace {outputNamespace};");
        sb.AppendLine();

        if (hasEntityHooks || hasListeners)
        {
            sb.AppendLine($"public sealed class {entity.ClassName}LifecycleInvoker : EntityLifecycleInvoker<{entity.FullyQualifiedName}>");
            sb.AppendLine("{");
            EmitListenerFields(sb, entity);
            EmitHookOverride(sb, entity, LifecycleKind.PrePersist, "InvokePrePersist");
            EmitHookOverride(sb, entity, LifecycleKind.PostPersist, "InvokePostPersist");
            EmitHookOverride(sb, entity, LifecycleKind.PreUpdate, "InvokePreUpdate");
            EmitHookOverride(sb, entity, LifecycleKind.PostUpdate, "InvokePostUpdate");
            EmitHookOverride(sb, entity, LifecycleKind.PreRemove, "InvokePreRemove");
            EmitHookOverride(sb, entity, LifecycleKind.PostRemove, "InvokePostRemove");
            EmitHookOverride(sb, entity, LifecycleKind.PostLoad, "InvokePostLoad");
            sb.AppendLine("}");
            sb.AppendLine();
        }

        if (entity.HasBatchLifecycle)
        {
            sb.AppendLine($"public sealed class {entity.ClassName}BatchLifecycleInvoker : BatchLifecycleInvoker<{entity.FullyQualifiedName}>");
            sb.AppendLine("{");
            EmitBatchHookOverride(sb, entity, LifecycleKind.PrePersistBatch, "InvokePrePersistBatch");
            EmitBatchHookOverride(sb, entity, LifecycleKind.PostPersistBatch, "InvokePostPersistBatch");
            EmitBatchHookOverride(sb, entity, LifecycleKind.PreUpdateBatch, "InvokePreUpdateBatch");
            EmitBatchHookOverride(sb, entity, LifecycleKind.PostUpdateBatch, "InvokePostUpdateBatch");
            EmitBatchHookOverride(sb, entity, LifecycleKind.PreRemoveBatch, "InvokePreRemoveBatch");
            EmitBatchHookOverride(sb, entity, LifecycleKind.PostRemoveBatch, "InvokePostRemoveBatch");
            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    private static bool IsEntityHook(LifecycleKind kind)
        => kind is LifecycleKind.PrePersist or LifecycleKind.PostPersist
            or LifecycleKind.PreUpdate or LifecycleKind.PostUpdate
            or LifecycleKind.PreRemove or LifecycleKind.PostRemove
            or LifecycleKind.PostLoad;

    private static void EmitListenerFields(StringBuilder sb, EntityModel entity)
    {
        for (var i = 0; i < entity.EntityListenerTypes.Count; i++)
        {
            var listener = entity.EntityListenerTypes[i];
            sb.AppendLine($"    private readonly {listener.TypeFqn} _entityListener{i} = new();");
        }
        if (entity.EntityListenerTypes.Any())
            sb.AppendLine();
    }

    private static void EmitHookOverride(
        StringBuilder sb,
        EntityModel entity,
        LifecycleKind kind,
        string invokerMethod)
    {
        var hooks = entity.LifecycleMethods.Where(m => m.Kind == kind).ToList();
        var listenerCalls = entity.EntityListenerTypes
            .SelectMany(l => l.Methods.Where(m => m.Kind == kind).Select(m => (l, m)))
            .ToList();
        if (hooks.Count == 0 && listenerCalls.Count == 0)
            return;

        sb.AppendLine($"    public override void {invokerMethod}({entity.FullyQualifiedName} entity)");
        sb.AppendLine("    {");
        foreach (var hook in hooks)
            sb.AppendLine($"        entity.{hook.MethodName}();");
        for (var i = 0; i < entity.EntityListenerTypes.Count; i++)
        {
            var listener = entity.EntityListenerTypes[i];
            foreach (var method in listener.Methods.Where(m => m.Kind == kind))
                sb.AppendLine($"        _entityListener{i}.{method.MethodName}(entity);");
        }
        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void EmitBatchHookOverride(
        StringBuilder sb,
        EntityModel entity,
        LifecycleKind kind,
        string invokerMethod)
    {
        var hooks = entity.LifecycleMethods.Where(m => m.Kind == kind).ToList();
        if (hooks.Count == 0)
            return;

        sb.AppendLine($"    public override void {invokerMethod}(IEnumerable<{entity.FullyQualifiedName}> entities)");
        sb.AppendLine("    {");
        foreach (var hook in hooks)
            sb.AppendLine($"        foreach (var entity in entities) entity.{hook.MethodName}();");
        sb.AppendLine("    }");
        sb.AppendLine();
    }
}
